OUTPUT_ARCH( "riscv" )
ENTRY( _entry )

SECTIONS
{
  /*
   * ensure that entry.S / _entry is at 0x80000000,
   * where qemu's -kernel jumps.
   */
  . = 0x80000000;

  .text : {
    kernel/entry.o(_entry)
    *(.text .text.*)
    . = ALIGN(0x1000);
    _trampoline = .;
    *(trampsec)
    . = ALIGN(0x1000);
    ASSERT(. - _trampoline == 0x1000, "error: trampoline larger than one page");
    PROVIDE(etext = .);
  }

  .rodata : {
    . = ALIGN(16);
    *(.srodata .srodata.*) /* do not need to distinguish this from .rodata */
    . = ALIGN(16);
    *(.rodata .rodata.*)
  }

  .data : {
    . = ALIGN(16);
    *(.sdata .sdata.*) /* do not need to distinguish this from .data */
    . = ALIGN(16);
    *(.data .data.*)
  }

  .kmods : {
    . = ALIGN(16);
    __kmods_start = .;
    KEEP(*(.kmods))
    __kmods_end = .;
    . = ALIGN(16);
  }

  .kmod_sys : {
    . = ALIGN(16);
    __kmod_sys_start = .;
    KEEP(*(.kmod_sys))
    __kmod_sys_end = .;
    . = ALIGN(16);
  }

  .kmod_hooks : {
    . = ALIGN(16);
    __kmod_hooks_start = .;
    KEEP(*(.kmod_hooks))
    __kmod_hooks_end = .;
    . = ALIGN(16);
  }

  .bss : {
    . = ALIGN(16);
    *(.sbss .sbss.*) /* do not need to distinguish this from .bss */
    . = ALIGN(16);
    *(.bss .bss.*)
  }

  PROVIDE(end = .);
}
