// 系统调用编号。
// 用户汇编桩（usys.S）把编号装入 a7，内核 syscall() 据此查表分发；
// 新增系统调用时需要同步修改这里、syscall.c 和 user/user.h。
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_pause  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_module_call 22
#define SYS_module_load 23
#define SYS_module_unload 24
#define SYS_setpriority 25
#define SYS_symlink 26
#define SYS_mkfifo 27
#define SYS_dumpstate 28
#define SYS_shmget 29
#define SYS_shmat 30
#define SYS_shmdt 31
#define SYS_shmrm 32
#define SYS_signal 33
#define SYS_sigkill 34
#define SYS_sigreturn 35
#define SYS_chmod 36
#define SYS_chown 37
#define SYS_getuid 38
#define SYS_geteuid 39
#define SYS_getgid 40
#define SYS_getegid 41
#define SYS_setuid 42
#define SYS_setgid 43
#define SYS_umask 44
#define SYS_mmap 45
#define SYS_munmap 46
#define SYS_mount 47
#define SYS_umount 48
#define SYS_swapout 49
#define SYS_swapinfo 50
#define SYS_clone 51
#define SYS_futex_wait 52
#define SYS_futex_wake 53
#define SYS_gettid 54
#define SYS_waitpid 55
#define SYS_set_tls 56
#define SYS_get_tls 57
#define SYS_tgkill 58
#define SYS_sigprocmask 59
