#!/usr/bin/perl -w

# 生成 usys.S：每个系统调用对应一段汇编桩。
# 桩代码把系统调用编号装入 a7，然后执行 ecall 陷入内核；
# 内核处理完返回后，再从 ecall 后的下一条指令继续，执行 ret。

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    # sbrk 返回 char*，为避免与 C 库里的旧符号冲突使用 sys_sbrk 名称；
    # 其余系统调用直接使用与 C 接口相同的函数名。
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";  # 装入系统调用编号
    print " ecall\n";               # 陷入内核
    print " ret\n";                 # 返回用户态后回到调用者
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
entry("module_call");
entry("module_load");
entry("module_unload");
entry("setpriority");
entry("symlink");
entry("mkfifo");
entry("dumpstate");
entry("shmget");
entry("shmat");
entry("shmdt");
entry("shmrm");
entry("signal");
entry("sigaction");
entry("sigpending");
entry("dup2");
entry("getcwd");
entry("chroot");
entry("fsync");
entry("nanosleep");
entry("clock_gettime");
entry("readv");
entry("writev");
entry("pipe2");
entry("poll");
entry("select");
entry("sigkill");
entry("sigreturn");
entry("chmod");
entry("chown");
entry("getuid");
entry("geteuid");
entry("getgid");
entry("getegid");
entry("setuid");
entry("setgid");
entry("umask");
entry("mmap");
entry("munmap");
entry("mount");
entry("umount");
entry("swapout");
entry("swapinfo");
entry("clone");
entry("exit_group");
entry("futex_wait");
entry("futex_wake");
entry("gettid");
entry("waitpid");
entry("waitpid_flags");
entry("set_tls");
entry("get_tls");
entry("tgkill");
entry("sigprocmask");
entry("setpgid");
entry("getpgid");
entry("killpg");
entry("tcsetpgrp");
entry("tcgetpgrp");
